name: hatif_pro
description: تطبيق تجاري لإدارة بيع وشراء الهواتف الذكية.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  drift: ^2.25.1
  sqlite3_flutter_libs: ^0.5.30
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.19.0
  uuid: ^4.5.1
  mobile_scanner: ^6.0.6
  image_picker: ^1.1.2
  file_picker: ^8.3.5
  share_plus: ^10.1.4
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  drift_dev: ^2.25.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
