create table if not exists products (
  id integer primary key,
  name text not null,
  category text not null,
  price integer not null default 0,
  cost integer not null default 0,
  stock integer not null default 0,
  imei text not null default '-',
  icon text not null default '▰',
  created_at timestamptz not null default now()
);

create table if not exists customers (
  name text primary key,
  type text not null,
  total text not null default '0 أوقية',
  created_at timestamptz not null default now()
);

create table if not exists warehouses (
  code text primary key,
  name text not null,
  branch text not null,
  manager text not null,
  capacity integer not null default 0,
  used integer not null default 0,
  status text not null default 'نشط',
  created_at timestamptz not null default now()
);

create table if not exists warehouse_stocks (
  id bigint generated by default as identity primary key,
  warehouse text not null,
  product text not null,
  category text not null,
  available integer not null default 0,
  reserved integer not null default 0,
  minimum integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists warehouse_stocks_unique_item
  on warehouse_stocks (warehouse, product);

create table if not exists invoices (
  number text primary key,
  customer text not null,
  issued_at timestamptz not null default now(),
  label_date text,
  total_label text,
  total_amount integer not null default 0,
  status text not null default 'مدفوعة',
  items jsonb not null default '[]'::jsonb
);

alter table products enable row level security;
alter table customers enable row level security;
alter table warehouses enable row level security;
alter table warehouse_stocks enable row level security;
alter table invoices enable row level security;

drop policy if exists "phone_pro_read_products" on products;
drop policy if exists "phone_pro_update_products" on products;
drop policy if exists "phone_pro_read_customers" on customers;
drop policy if exists "phone_pro_read_warehouses" on warehouses;
drop policy if exists "phone_pro_read_warehouse_stocks" on warehouse_stocks;
drop policy if exists "phone_pro_read_invoices" on invoices;
drop policy if exists "phone_pro_insert_invoices" on invoices;

create policy "phone_pro_read_products" on products for select using (true);
create policy "phone_pro_update_products" on products for update using (true) with check (true);
create policy "phone_pro_read_customers" on customers for select using (true);
create policy "phone_pro_read_warehouses" on warehouses for select using (true);
create policy "phone_pro_read_warehouse_stocks" on warehouse_stocks for select using (true);
create policy "phone_pro_read_invoices" on invoices for select using (true);
create policy "phone_pro_insert_invoices" on invoices for insert with check (true);

insert into products (id, name, category, price, cost, stock, imei, icon) values
  (1, 'iPhone 15 Pro Max 256GB', 'هواتف جديدة', 630000, 570000, 6, '353921102938475', '▰'),
  (2, 'Samsung Galaxy A55 5G', 'هواتف جديدة', 238000, 205000, 12, '358240116543902', '▱'),
  (3, 'Xiaomi Redmi Note 13', 'هواتف جديدة', 146000, 119000, 4, '869120449218330', '▰'),
  (4, 'iPhone 12 مستعمل 128GB', 'هواتف مستعملة', 198000, 145000, 2, '356938035643809', '▧'),
  (5, 'Samsung S22 Ultra مستعمل', 'هواتف مستعملة', 275000, 221000, 1, '351234987650128', '▧'),
  (6, 'شاحن USB-C سريع 25W', 'إكسسوارات', 12000, 6200, 8, '-', '⚡'),
  (7, 'سماعة AirPods Pro', 'إكسسوارات', 78000, 52000, 15, '-', '◎'),
  (8, 'حماية شاشة زجاجية', 'إكسسوارات', 2500, 900, 32, '-', '□')
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  cost = excluded.cost,
  stock = excluded.stock,
  imei = excluded.imei,
  icon = excluded.icon;

insert into customers (name, type, total) values
  ('خديجة بنت سالم', 'عميل ذهبي', '2,390,000 أوقية'),
  ('شركة الساحل', 'عميل شركات', '8,145,000 أوقية'),
  ('محمد الأمين', 'عميل نقدي', '928,000 أوقية'),
  ('مورد التقنيات الحديثة', 'مورد', '12,800,000 أوقية')
on conflict (name) do update set type = excluded.type, total = excluded.total;

insert into warehouses (code, name, branch, manager, capacity, used, status) values
  ('WH-NKC', 'المستودع الرئيسي - نواكشوط', 'فرع نواكشوط', 'محمد الأمين', 120, 80, 'نشط'),
  ('WH-NDB', 'مستودع نواذيبو', 'فرع نواذيبو', 'خديجة بنت سالم', 75, 43, 'نشط'),
  ('WH-ACC', 'مستودع القطع والإكسسوارات', 'فرع نواكشوط', 'شركة الساحل', 220, 146, 'مراجعة')
on conflict (code) do update set
  name = excluded.name,
  branch = excluded.branch,
  manager = excluded.manager,
  capacity = excluded.capacity,
  used = excluded.used,
  status = excluded.status;

insert into warehouse_stocks (warehouse, product, category, available, reserved, minimum) values
  ('المستودع الرئيسي - نواكشوط', 'iPhone 15 Pro Max 256GB', 'هواتف جديدة', 4, 1, 2),
  ('المستودع الرئيسي - نواكشوط', 'Samsung Galaxy A55 5G', 'هواتف جديدة', 7, 2, 3),
  ('مستودع نواذيبو', 'Xiaomi Redmi Note 13', 'هواتف جديدة', 3, 0, 4),
  ('مستودع نواذيبو', 'iPhone 12 مستعمل 128GB', 'هواتف مستعملة', 2, 0, 1),
  ('مستودع القطع والإكسسوارات', 'شاحن USB-C سريع 25W', 'إكسسوارات', 8, 3, 10),
  ('مستودع القطع والإكسسوارات', 'حماية شاشة زجاجية', 'إكسسوارات', 32, 6, 20)
on conflict (warehouse, product) do update set
  category = excluded.category,
  available = excluded.available,
  reserved = excluded.reserved,
  minimum = excluded.minimum;

insert into invoices (number, customer, label_date, total_label, total_amount, status) values
  ('#H1048', 'خديجة بنت سالم', 'اليوم 11:42', '286,000 أوقية', 286000, 'مدفوعة'),
  ('#H1047', 'عميل نقدي', 'اليوم 10:18', '78,000 أوقية', 78000, 'مدفوعة'),
  ('#H1046', 'شركة الساحل', 'أمس 16:02', '1,120,000 أوقية', 1120000, 'آجلة'),
  ('#H1045', 'محمد الأمين', 'أمس 13:31', '198,000 أوقية', 198000, 'ضمان'),
  ('#H1044', 'عميل نقدي', 'الخميس 19:20', '12,000 أوقية', 12000, 'مدفوعة')
on conflict (number) do update set
  customer = excluded.customer,
  label_date = excluded.label_date,
  total_label = excluded.total_label,
  total_amount = excluded.total_amount,
  status = excluded.status;
